import { expect, test } from "@playwright/test";

test("Barbu review survives learning hands and other games without sharing their state", async ({ page }, info) => {
  const errors: string[] = [];
  page.on("pageerror", error => errors.push(error.message));
  const key = "barbu.savedPlayRun.v1";
  await page.goto("/");
  await page.getByRole("button", { name: "Open Barbu", exact: true }).click();
  await page.getByRole("button", { name: "Play Barbu", exact: true }).click();
  await page.screenshot({ path: info.outputPath("barbu-intro.png"), fullPage: true });
  await page.getByRole("button", { name: "Start hand", exact: true }).click();
  await page.locator(".full-hand-card.legal").first().click();
  await page.getByRole("button", { name: "Play card", exact: true }).click();
  await expect(page.getByRole("button", { name: "Next trick", exact: true })).toBeVisible();
  const saved = await page.evaluate(key => localStorage.getItem(key), key);
  await page.getByRole("button", { name: "Table", exact: true }).first().click();
  await page.getByRole("tab", { name: "Learn", exact: true }).click();
  await page.getByRole("button", { name: /^Try cards: Domino\b/ }).click();
  await expect(page.getByLabel("Your Domino hand")).toBeVisible();
  const place = page.getByRole("button", { name: "Place card", exact: true });
  if (await place.isEnabled()) await place.click();
  else await page.getByRole("button", { name: "Pass", exact: true }).click();
  await page.screenshot({ path: info.outputPath("barbu-domino.png"), fullPage: true });
  expect(await page.evaluate(key => localStorage.getItem(key), key)).toBe(saved);
  await page.getByRole("button", { name: "Table", exact: true }).first().click();
  await page.getByRole("button", { name: "Games", exact: true }).click();
  await page.getByRole("button", { name: "Open Hearts", exact: true }).click();
  await page.getByRole("button", { name: "Play Hearts", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: "Open Barbu", exact: true }).click();
  await page.getByRole("button", { name: "Continue Play Barbu", exact: true }).click();
  await expect(page.getByRole("button", { name: "Next trick", exact: true })).toBeVisible();
  const restored = await page.evaluate(key => JSON.parse(localStorage.getItem(key)!), key);
  expect(restored.fullHand).toEqual(JSON.parse(saved!).fullHand);
  await page.getByRole("button", { name: "Next trick", exact: true }).click();
  await page.screenshot({ path: info.outputPath("barbu-resumed-hand.png"), fullPage: true });
  await page.setViewportSize({ width: 320, height: 568 });
  await expect(page.locator(".full-hand-cards")).toBeVisible();
  await expect(page.getByRole("button", { name: "Play card", exact: true })).toBeInViewport();
  await page.screenshot({ path: info.outputPath("barbu-compact-hand.png"), fullPage: true });
  expect(errors).toEqual([]);
});
