import type { GameReference } from "./referenceCatalog";
export const canastaReference: GameReference = {
  id: "canasta", title: "Canasta", family: "Rummy", baselineLabel: "Modern American",
  baseline: "Modern American Canasta: Pagat table rules",
  overview: "You and Barbu share melds and a score against West and East. Build seven-card canastas, protect your partnership from penalties, and aim for 8500 points.",
  sections: [
    { id: "deal", title: "Players and deal", body: "Four players use two packs and four jokers. Each receives 13 cards. Play moves clockwise from the dealer's left; the dealer rotates after each hand. The discard pile begins empty." },
    { id: "melds", title: "Melds", body: "Meld 3 to 7 cards of one rank. Twos and jokers are wild; a mixed meld needs at least two natural cards and no more than two wilds. Sevens stay natural. Mixed aces may start only in the opening; natural aces stay natural. After opening, other melds need five natural cards before you add wilds. A separate wild meld is allowed; complete it before using wilds elsewhere. A closed rank cannot be melded by either side." },
    { id: "opening", title: "Opening", body: "Open with 125 points below 3000, 155 below 5000, or 180 at 5000 and above. Include a wholly natural meld or a wild meld. A seven-card natural or wild splash waives the minimum. Only cards already in your hand count toward opening. The first partnership to open reserves four stock cards, the other three, after discarding; those cards join the opener's next turn. There is no bonus once the bottom eight have been reached." },
    { id: "pile", title: "Drawing and discarding", body: "Draw a stock card, or use two matching natural cards from hand to meld the top discard and take the whole pile. An existing matching meld must have room for all three. End your turn with a discard. Threes cannot be discarded; wilds can be discarded when going out, or if your hand was all wild before drawing another wild. On an empty pile, avoid aces, sevens, and closed ranks unless no permitted alternative remains." },
    { id: "threes", title: "Threes", body: "Expose threes and draw replacements. Before your partnership opens, you may keep one three for a straight. A last-stock three ends play immediately and stays in hand. For each colour, one, two, three, or four exposed threes count 100, 300, 500, or 1000: negative with no canasta, zero with one, positive with two or more." },
    { id: "finish", title: "Going out", body: "Complete two canastas, meld down to one card, and discard it to go out for 100 extra points. You may go out without asking your partner. When the stock is empty, play continues through legal pile pickups until someone needs a stock draw." },
    { id: "values", title: "Card values", body: "Jokers count 50; aces and twos 20; eights through kings 10; fours through sevens 5. A three left in hand counts 5 against your team. Exposed threes use their separate bonus or penalty instead." },
    { id: "score", title: "Scoring", body: "Mixed canastas earn 300; natural canastas 500; natural aces and sevens 2500. Wild canastas earn 3000 for all twos, 2500 with all four jokers, or 2000 otherwise. Melded card values are added with a canasta and subtracted without one; cards in hand are always subtracted. Unfinished natural aces or sevens cost 2500. An unfinished wild meld costs 2000, or 2500 with four jokers. Each player's three or more unmelded aces or sevens costs 1500 per rank. These penalties also apply with one completed canasta." },
    { id: "special", title: "Special hands", body: "Before your team opens, draw from stock and reveal 14 cards without discarding: one of every rank plus a joker (straight, 3000); seven distinct natural pairs (2500); seven pairs including twos, aces, and sevens (2000); or two natural four-of-a-kinds and two natural triples (garbage, 2000). No threes or jokers in pairs, and no wilds or threes in garbage. Your team scores only the special-hand award; opponents score normally." }
  ], contracts: [],
  variants: [{ id: "profile", title: "Modern American table agreements", note: "This table uses Pagat's Modern American profile: the rule of five, delayed opening bonuses, and three special-hand families. Canasta League of America tables may use additional special hands, different awards, and other agreements. Classic Canasta is a separate ruleset." }]
};
